name: Monthly issue metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'  # 每月 1 日 02:03 (UTC) 运行一次，可按需修改

permissions:
  contents: read

jobs:
  issue-metrics:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    env:
      # 报告标题（可以改）
      REPORT_TITLE: "Monthly issue metrics report"
    steps:
      - name: Checkout repo (optional)
        uses: actions/checkout@v4

      - name: Get dates for last month
        shell: bash
        run: |
          first_day=$(date -d "last month" +%Y-%m-01)
          last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)
          echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

      - name: Run issue-metrics tool (generate JSON)
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SEARCH_QUERY: 'repo:facebook/react is:issue created:${{ env.last_month }}'
          OUTPUT_FILE: issue_metrics.json
          REPORT_TITLE: "Monthly issue metrics"

      - name: Create GitHub Issue from report
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: ${{ env.REPORT_TITLE }}
          token: ${{ secrets.GH_TOKEN }}
          content-filepath: ./issue_metrics.md
