name: Issue Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  issue-metrics:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Run issue metrics
        uses: github/issue-metrics@v2
        with:
          args: --search "repo:facebook/react is:issue created:2025-01-01..2025-09-21"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
